name: build shared cache

on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string
        default: main
      version:
        required: true
        type: string
    secrets:
      repository:
        required: false


jobs:
  build-cache:
    # first create all empty collections, because document type rules must reference a collection ID
    name: build cache 
    runs-on: self-hosted

    steps:
      - name: check input
        run: |
          echo "repository: ${{ secrets.repository }}"
          echo "branch ${{ inputs.branch }}"
          echo "version ${{ inputs.version }}"

      - name: shared cache
        id: shared-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: shared-${{ inputs.version }}

      - name: checkout shared
        uses: actions/checkout@v2
        if: steps.shared-cache.outputs.cache-hit != 'true'
        with:
          repository: ${{ secrets.repository }}
          ref: ${{ inputs.branch }}
          path: './shared'

      - name: build cache shared
        id: build-cache-shared
        if: steps.shared-cache.outputs.cache-hit != 'true'
        run: |
          [ -d ~/.shared ] || mkdir -p ~/.shared
          cp -avr ./shared/.scripts/*.* ~/.shared
          

