name: cache collection ids

on:
  workflow_call:
    inputs:
      shared-repository:
        required: false
        type: string
        default: something-non-existant
      shared-repository-branch:
        required: false
        type: string
        default: main
      scripts-version:
        required: true
        type: string
    secrets: 
      appwrite-endpoint:
        required: true
      appwrite-project:
        required: true
      appwrite-apikey:
        required: true
      github-token:
        required: true

env:
  APPWRITE_PROJECT: ${{ secrets.appwrite-project }}
  APPWRITE_APIKEY: ${{ secrets.appwrite-apikey }}
  APPWRITE_ENDPOINT: ${{ secrets.appwrite-endpoint }}

jobs:
  build-cache:
    # first create all empty collections, because document type rules must reference a collection ID
    name: cache 
    runs-on: self-hosted

    steps:

      - name: scripts cache
        id: scripts-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: scripts-v${{ inputs.scripts-version }}

      - name: checkout shared
        uses: actions/checkout@v2
        if: steps.scripts-cache.outputs.cache-hit != 'true'
        with:
          ref: ${{ inputs.shared-repository-branch }}
          repository: ${{ inputs.shared-repository }}
          path: './shared'
          token: ${{ secrets.github-token }} 

      - name: build cache scripts
        id: build-cache-scripts
        if: steps.scripts-cache.outputs.cache-hit != 'true'
        run: |
          [ -d ~/.shared ] || mkdir -p ~/.shared
          cp -r ./shared/.scripts ~/.shared

      - name: get latest commit
        id: latest-commit
        run: |
          . ~/.shared/get_latest_commit.sh \
              "${{ inputs.shared-repository }}" \
              "${{ inputs.shared-repository-branch }}" \
              "${{ secrets.github-token }}" 
          commit=$(cat _get_latest_commit.txt)
          echo $commit
          echo "::set-output name=commit::$commit"

      - name: appwrite cache
        id: appwrite-cache
        uses: actions/cache@v2
        with:
          path: ~/.appwrite/cache
          key: ${{ secrets.appwrite-project }}-${{ steps.latest-commit.outputs.commit }}

      - name: build cache collections
        id: build-cache-collections
        if: steps.appwrite-cache.outputs.cache-hit != 'true'

        run: |
          [ -d ~/.appwrite/cache ] || mkdir -p ~/.appwrite/cache
          . ~/.shared/list_collections.sh 100
          collections=$(cat _list_collections.txt)
          cp _list_collections.txt ~/.appwrite/cache/collections.json
          variables=$(echo $collections | jq '[ .[] | { key: "collection_\(.name)", value: ."$id" }]')
          . prepare_env.sh "$variables"
          cp _prepare_env.txt ~/.appwrite/cache/env_collections.sh

      - name: build cache functions
        id: build-cache-functions
        if: steps.appwrite-cache.outputs.cache-hit != 'true'

        run: |
          [ -d ~/.appwrite/cache ] || mkdir -p ~/.appwrite/cache
          . ~/.shared/list_functions.sh 100
          functions=$(cat _list_functions.txt)
          cp _list_functions.txt ~/.appwrite/cache/functions.json
          variables=$(echo $functions | jq '[ .[] | { key: "function_\(.name)", value: ."$id" }]')
          . prepare_env.sh "$variables"
          cp _prepare_env.txt ~/.appwrite/cache/env_functions.sh
