name: build appwrite cache

on:
  workflow_call:
    inputs:
      shared-cache-version:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets: 
      appwrite-endpoint:
        required: true
      appwrite-project:
        required: true
      appwrite-apikey:
        required: true

env:
  APPWRITE_PROJECT: ${{ secrets.appwrite-project }}
  APPWRITE_APIKEY: ${{ secrets.appwrite-apikey }}
  APPWRITE_ENDPOINT: ${{ secrets.appwrite-endpoint }}

jobs:
  build-cache:
    # first create all empty collections, because document type rules must reference a collection ID
    name: cache 
    runs-on: self-hosted

    steps:

      - name: shared cache
        id: shared-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: shared-${{ inputs.shared-cache-version }}

      - name: appwrite cache
        id: appwrite-cache
        uses: actions/cache@v2
        with:
          path: ~/.appwrite/cache
          key: ${{ secrets.appwrite-project }}-${{ inputs.version }}

      - name: build cache collections
        id: build-cache-collections
        if: steps.appwrite-cache.outputs.cache-hit != 'true'

        run: |
          [ -d ~/.appwrite/cache ] || mkdir -p ~/.appwrite/cache
          cd ~/.shared
          . list-collections.sh 100
          collections=$(cat _list_collections.txt)
          cp _list_collections.txt ~/.appwrite/cache/collections.json
          variables=$(echo $collections | jq '[ .[] | { key: "collection_\(.name)", value: ."$id" }]')
          . prepare-env.sh "$variables"
          cp _prepare_env.txt ~/.appwrite/cache/env_collections.sh
          . prepare-build.sh "$variables"
          echo "::set-output name=collection-build-parameters::$(cat _prepare_build.txt)"

      - name: build cache functions
        id: build-cache-functions
        if: steps.appwrite-cache.outputs.cache-hit != 'true'

        run: |
          [ -d ~/.appwrite/cache ] || mkdir -p ~/.appwrite/cache
          cd ~/.shared
          . list-functions.sh 100
          functions=$(cat _list_functions.txt)
          cp _list_functions.txt ~/.appwrite/cache/functions.json
          variables=$(echo $functions | jq '[ .[] | { key: "function_\(.name)", value: ."$id" }]')
          . prepare-env.sh "$variables"
          cp _prepare_env.txt ~/.appwrite/cache/env_functions.sh
          . prepare-build.sh "$variables"
          echo "::set-output name=function-build-parameters::$(cat _prepare_build.txt)"

      - name: prepare build parameters
        id: prepare-build-parameters
        if: steps.appwrite-cache.outputs.cache-hit != 'true'

        run: |
          [ -d ~/.appwrite/cache ] || mkdir -p ~/.appwrite/cache

          cd ~/.appwrite/cache
          echo '--dart-define APPWRITE_PROJECT="${{ secrets.appwrite-project }}"
          --dart-define APPWRITE_ENDPOINT="${{ secrets.appwrite-endpoint }}"
          ${{ steps.build-cache-collections.outputs.collection-build-parameters }}
          ${{ steps.build-cache-functions.outputs.function-build-parameters }}' > build-parameters.txt

          cat build-parameters.txt
