name: build shared cache

on:
  workflow_call:
    inputs:
      shared-repository:
        required: false
        type: string
        default: something-non-existant
      shared-repository-branch:
        required: false
        type: string
        default: main
      version:
        required: true
        type: string

jobs:
  build-cache:
    # first create all empty collections, because document type rules must reference a collection ID
    name: cache 
    runs-on: self-hosted

    steps:

      - name: shared cache
        id: shared-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: shared-${{ inputs.version }}

      - name: checkout shared
        uses: actions/checkout@v2
        if: steps.shared-cache.outputs.cache-hit != 'true'
        with:
          repository: ${{ inputs.shared-repository }}
          ref: ${{ inputs.shared-repository-branch }}
          path: './shared'

      - name: build cache shared
        id: build-cache-shared
        if: steps.shared-cache.outputs.cache-hit != 'true'
        run: |
          [ -d ~/.shared ] || mkdir -p ~/.shared
          cp -r ./shared/.scripts ~/.shared

