name: deploy function reusable workflow

on:
  workflow_call:
    inputs:
      files:
        type: string
        required: true
      path:
        type: string
        required: true
      scripts-cache-version:
        type: string
        required: true
      appwrite-cache-version:
        type: string
        required: true
    secrets: 
      appwrite-endpoint:
        required: true
      appwrite-project:
        required: true
      appwrite-apikey:
        required: true

env:
  APPWRITE_PROJECT: ${{ secrets.appwrite-project }}
  APPWRITE_APIKEY: ${{ secrets.appwrite-apikey }}
  APPWRITE_ENDPOINT: ${{ secrets.appwrite-endpoint }}

jobs:
  infra:
    name: deploy function infra
    runs-on: self-hosted

    strategy:
      fail-fast: true
      matrix: ${{ fromJson(inputs.files) }}

    steps:
      # load the cache
      - name: scripts cache
        id: scripts-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: scripts-${{ inputs.scripts-cache-version }}

      - name: appwrite cache
        id: appwrite-cache
        uses: actions/cache@v2
        with:
          path: ~/.appwrite/cache
          key: ${{ secrets.appwrite-project }}-${{ inputs.appwrite-cache-version }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: './artifacts'

      - name: get function name
        id: get-function-name
        run: |
          functionJson=$(cat ${{ inputs.path }}/${{ matrix.files }})
          functionName=$(jq -r '.name' <<< $functionJson)
          echo "::set-output name=functionName::$functionName"

      - name: get function id
        id: get-function-id
        run: |
          .  ~/.appwrite/cache/env_functions.sh
          name="${{ steps.get-function-name.outputs.functionName }}"
          functionId=$(eval "echo \$$(echo functions_${name//-/_} | tr [:lower:] [:upper:] )"")
          echo $functionId
          # cd artifacts/.scripts
          # . get_function_id.sh "${{ steps.get-function-name.outputs.functionName }}"
          # functionId=$(cat _get_function_id.txt)
          echo "::set-output name=functionId::$functionId"

      - name: create function
        id: create-function
        if: ${{ steps.get-function-id.outputs.functionId == '' }}
        run: |
          .  ~/.shared/create_function.sh \
            "${{ steps.get-function-name.outputs.functionName }}" \
            "${{ inputs.path }}/${{ matrix.files }}"
          functionId=$(cat _create_function.txt)
          echo "::set-output name=functionId::$functionId"

      - name: set functionId
        id: set-function-id
        run: |
          if [ "${{ steps.get-function-id.outputs.functionId }}" == "" ]; then
            echo "::set-output name=functionId::${{ steps.create-function.outputs.functionId}}"
          else
            echo "::set-output name=functionId::${{ steps.get-function-id.outputs.functionId}}"
          fi

      - name: check
        run: |
          echo "functionId: ${{ steps.set-function-id.outputs.functionId }}"

