name: deploy function reusable workflow

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
        default: "0.0.0"
      shared-cache-version:
        type: string
        required: true
      appwrite-cache-version:
        type: string
        required: true
    secrets: 
      appwrite-endpoint:
        required: true
      appwrite-project:
        required: true
      appwrite-apikey:
        required: true
      function-apikey:
        required: true
      evernote-token:
        required: false

env:
  APPWRITE_PROJECT: ${{ secrets.appwrite-project }}
  APPWRITE_APIKEY: ${{ secrets.appwrite-apikey }}
  APPWRITE_ENDPOINT: ${{ secrets.appwrite-endpoint }}
  APPWRITE_FUNCTION_APIKEY: ${{ secrets.function-apikey }}
  EVERNOTE_TOKEN: ${{ secrets.evernote-token }}

jobs:


  infra:
    name: deploy function infra
    runs-on: self-hosted

    outputs:
      functionId: ${{ steps.get-function-id.outputs.functionId }}
      
    steps:
      - name: shared cache
        id: shared-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: shared-${{ inputs.shared-cache-version }}

      - name: shared cache check
        if: ${{ steps.shared-cache.outputs.cache-hit != 'true' }}
        run: exit 1

      - name: appwrite cache
        id: appwrite-cache
        uses: actions/cache@v2
        with:
          path: ~/.appwrite/cache
          key: ${{ secrets.appwrite-project }}-${{ inputs.appwrite-cache-version }}

      - name: appwrite cache check
        if: ${{ steps.appwrite-cache.outputs.cache-hit != 'true' }}
        run: exit 1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: './artifacts'

      - name: get function name
        id: get-function-name
        run: |
          functionName=$(cat $GITHUB_WORKSPACE/artifacts/.ci/function.json | jq -r '.name')
          echo "::set-output name=functionName::$functionName"

      - name: get function id
        id: get-function-id
        run: |
          cd ~/.shared
          . get_function_id.sh "${{ steps.get-function-name.outputs.functionName }}"
          functionId=$(cat _get_function_id.txt)
          echo "::set-output name=functionId::$functionId"

      - name: fail if function not found
        id: fail-if-function-not-found
        if: ${{ steps.get-function-id.outputs.functionId == '' }}
        run: exit 1

      - name: update function
        id: update-function
        if: ${{ steps.get-function-id.outputs.functionId != '' }}
        run: |
          . ~/.appwrite/cache/env_collections.sh

          cd ~/.shared
          . update_function.sh \
            "${{ steps.get-function-name.outputs.functionName }}" \
            "${{ steps.get-function-id.outputs.functionId }}" \
            "$GITHUB_WORKSPACE/artifacts/.ci/function.json"

  build:
    name: build and upload code    
    runs-on: self-hosted

    needs:
      - infra

    outputs: 
      tagId: ${{ steps.create-tag.outputs.tagId }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: './artifacts'

      - name: shared cache
        id: shared-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: shared-${{ inputs.shared-cache-version }}

      - name: shared cache check
        if: ${{ steps.shared-cache.outputs.cache-hit != 'true' }}
        run: exit 1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: build
        id: build
        run: |
          npm install -g bundle-deps

          cd artifacts/
          npm ci --include dev
          npm test

          pkgName=$(npm pkg get name | tr -d '"')
          echo $pkgName
          echo "version: ${{ inputs.version }}"
          npm pkg set version="${{ inputs.version }}"

          bundle-deps
          json=$(npm pack)
          tgzFile=$(echo $json | grep "^$pkgName.*\.tgz")
          codeFile=${tgzFile%.tgz}.tar.gz

          mv -- "$tgzFile" "$codeFile"

          echo "package created: $codeFile"
          echo "::set-output name=codeFile::$codeFile"

      - name: create tag
        id: create-tag
        run: |
          cd ~/.shared
          . create_tag.sh \
            "${{ needs.infra.outputs.functionId }}" \
            "${{ steps.build.outputs.codeFile }}" \
            ".ci/tag.json" \
            "$GITHUB_WORKSPACE/artifacts/"
          tagId=$(cat _create_tag.txt)
          echo "::set-output name=tagId::$tagId"

      - name: check
        run: | 
          echo "tagId: ${{ steps.create-tag.outputs.tagId }}"

  deploy:
    name: update tag    
    runs-on: self-hosted

    needs:
      - infra
      - build

    steps:

      - name: shared cache
        id: shared-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: shared-${{ inputs.shared-cache-version }}

      - name: shared cache check
        if: ${{ steps.shared-cache.outputs.cache-hit != 'true' }}
        run: exit 1
        
      - name: deploy tag
        id: deploy-tag
        run: |
          cd ~/.shared
          . update_function_tag.sh \
            "${{ needs.infra.outputs.functionId }}" \
            "${{ needs.build.outputs.tagId }}"


