name: deploy function reusable workflow

on:
  workflow_call:
    inputs:
      function-name:
        type: string
        required: true
      version:
        type: string
        required: false
        default: "0.0.0"
      infra-repository:
        required: true
        type: string
      infra-repository-branch:
        required: false
        type: string
        default: main
      github-api-url:
        type: string
        required: true
      github-actor:
        type: string
        required: true
    secrets: 
      appwrite-endpoint:
        required: true
      appwrite-project:
        required: true
      appwrite-apikey:
        required: true
      function-apikey:
        required: true
      github-token:
        required: true

env:
  APPWRITE_PROJECT: ${{ secrets.appwrite-project }}
  APPWRITE_APIKEY: ${{ secrets.appwrite-apikey }}
  APPWRITE_ENDPOINT: ${{ secrets.appwrite-endpoint }}
  APPWRITE_FUNCTION_NAME: ${{ inputs.function-name }}
  APPWRITE_FUNCTION_APIKEY: ${{ secrets.function-apikey }}

jobs:


  infra:
    name: deploy function infra
    runs-on: self-hosted

    outputs:
      functionId: ${{ steps.get-function-id.outputs.functionId }}

    steps:
      - name: checkout infra
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.infra-repository-branch }}
          repository: ${{ inputs.infra-repository }}
          path: './infra'
          token: ${{ secrets.github-token }} 

      - name: get latest commit
        id: latest-commit
        run: |
          cd infra/.scripts
          . get_latest_commit.sh \
              "${{ inputs.github-api-url }}" \
              "${{ inputs.infra-repository }}" \
              "${{ inputs.infra-repository-branch }}" \
              "${{ inputs.github-actor }}" \
              "${{ secrets.github-token }}" 
          commit=$(cat _get_latest_commit.txt)
          echo $commit
          echo "::set-output name=commit::$commit"

      - name: use cache
        id: use-cache
        uses: actions/cache@v2
        with:
          path: ~/.appwrite/cache
          key: ${{ secrets.appwrite-project }}-${{ steps.latest-commit.outputs.commit }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: './artifacts'

      - name: get function id
        id: get-function-id
        run: |
          cd infra/.scripts
          . get_function_id.sh "${{ env.APPWRITE_FUNCTION_NAME }}"
          functionId=$(cat _get_function_id.txt)
          echo "::set-output name=functionId::$functionId"

      - name: fail if function does not exist
        id: fail-if-not-found
        if: ${{ steps.get-function-id.outputs.functionId == '' }}
        run: exit 1

      - name: update function
        id: update-function
        if: ${{ steps.get-function-id.outputs.functionId != '' }}
        run: |
          . ~/.appwrite/cache/env_collections.sh
          cd infra/.scripts
          . update_function.sh \
            "${{ env.APPWRITE_FUNCTION_NAME }}" \
            "${{ steps.get-function-id.outputs.functionId }}" \
            "$GITHUB_WORKSPACE/artifacts/.ci/function.json"

  build:
    name: build and upload code    
    runs-on: self-hosted

    needs:
      - infra

    outputs: 
      tagId: ${{ steps.create-tag.outputs.tagId }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: './artifacts'

      - name: checkout infra
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.infra-repository-branch }}
          repository: ${{ inputs.infra-repository }}
          path: './infra'
          token: ${{ secrets.github-token }} 
        
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: build
        id: build
        env:
          CI: true  
        run: |
          npm install -g bundle-deps

          cd artifacts/
          npm ci --include dev
          npm test

          pkgName=$(npm pkg get name | tr -d '"')
          echo $pkgName
          echo "version: ${{ inputs.version }}"
          npm pkg set version="${{ inputs.version }}"

          bundle-deps
          json=$(npm pack)
          tgzFile=$(echo $json | grep "^$pkgName.*\.tgz")
          codeFile=${tgzFile%.tgz}.tar.gz

          mv -- "$tgzFile" "$codeFile"

          echo "package created: $codeFile"
          echo "::set-output name=codeFile::$codeFile"

      - name: create tag
        id: create-tag
        run: |
          cd infra/.scripts
          . create_tag.sh \
            "${{ needs.infra.outputs.functionId }}" \
            "${{ steps.build.outputs.codeFile }}" \
            ".ci/tag.json" \
            "$GITHUB_WORKSPACE/artifacts/"
          functionId=$(cat _create_tag.txt)
          echo "::set-output name=tagId::$tagId"

      - name: check
        run: | 
          echo "tagId: ${{ steps.create-tag.outputs.tagId }}"

  deploy:
    name: update tag    
    runs-on: self-hosted

    needs:
      - infra
      - build

    steps:

      - name: checkout infra
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.infra-repository-branch }}
          repository: ${{ inputs.infra-repository }}
          path: './infra'
          token: ${{ secrets.github-token }} 
        
      - name: deploy tag
        id: deploy-tag
        run: |
          cd infra/.scripts
          . update_function_tag.sh \
            "${{ needs.infra.outputs.functionId }}" \
            "${{ needs.build.outputs.tagId }}"


