name: create empty collection reusable workflow

on:
  workflow_call:
    inputs:
      files:
        type: string
        required: true
      path:
        type: string
        required: true
      shared-cache-version:
        type: string
        required: true
    secrets: 
      appwrite-endpoint:
        required: true
      appwrite-project:
        required: true
      appwrite-apikey:
        required: true

env:
  APPWRITE_PROJECT: ${{ secrets.appwrite-project }}
  APPWRITE_APIKEY: ${{ secrets.appwrite-apikey }}
  APPWRITE_ENDPOINT: ${{ secrets.appwrite-endpoint }}

jobs:
  init:
    # first create all empty collections, because document type rules must reference a collection ID
    name: create empty
    runs-on: self-hosted

    strategy:
      fail-fast: true
      matrix: ${{ fromJson(inputs.files) }}

    outputs:
      collectionId: ${{ steps.set-collection-id.outputs.collectionId }}
      collectionName: "${{ steps.get-collection-name.outputs.collectionName }}"

    steps:
      # load the cache
      - name: shared cache
        id: shared-cache
        uses: actions/cache@v2
        with:
          path: ~/.shared
          key: shared-${{ inputs.shared-cache-version }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: './artifacts'

      - name: get collection name
        id: get-collection-name
        run: |
          collectionJson=$(cat ${{ inputs.path }}/${{ matrix.files }})
          collectionName=$(jq -r '.name' <<< $collectionJson)
          echo "::set-output name=collectionName::$collectionName"

      - name: check cache
        run: ls ~/.shared/

      - name: get collection id
        id: get-collection-id
        run: |
          . ~/.shared/get_collection_id.sh "${{ steps.get-collection-name.outputs.collectionName }}"
          collectionId=$(cat _get_collection_id.txt)
          echo "::set-output name=collectionId::$collectionId"

      - name: create collection
        id: create-collection
        if: ${{ steps.get-collection-id.outputs.collectionId == '' }}
        run: |
          . ~/.shared/create_collection.sh \
            "${{ steps.get-collection-name.outputs.collectionName }}" 
          collectionId=$(cat _create_collection.txt)
          echo "::set-output name=collectionId::$collectionId"

      - name: set collectionId
        id: set-collection-id
        run: |
          if [ "${{ steps.get-collection-id.outputs.collectionId }}" == "" ]; then
            echo "::set-output name=collectionId::${{ steps.create-collection.outputs.collectionId}}"
          else
            echo "::set-output name=collectionId::${{ steps.get-collection-id.outputs.collectionId}}"
          fi

      - name: check
        run: |
          echo "collectionId: ${{ steps.set-collection-id.outputs.collectionId }}"
          echo "collectionName: ${{ steps.get-collection-name.outputs.collectionName }}"

